language: php

sudo: true

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.1
    - php: nightly

services:
  - mysql

before_script:
  # prevent MySQL went away error
  - mysql -u root -e 'SET @@GLOBAL.wait_timeout=28800;'

  # Create a new database and add all priveleges
  - mysql -u root -e "create database IF NOT EXISTS skipper;"

  # Current DIR
  - pwd

  # Move up one directory
  - cd ../

  # Create a New Laravel App
  - composer create-project --prefer-dist laravel/laravel skipper-app

  # CD into the new laravel app
  - cd skipper-app

  # Include Skipper Package
  - composer require anla/skipper

  # Remove the current version
  - rm -rf vendor/anla/skipper

  # Move this build into the skipper folder
  - mv $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../skipper-app/vendor/anla/skipper

  # Move up one folder and rename skipper-app to skipper
  - cd ../
  - mv skipper-app skipper
  - cd skipper
  - composer dump-autoload

  # Add the database credentials
  - sed 's/DB_DATABASE=homestead/DB_DATABASE=skipper/g' .env > environment
  - sed 's/DB_USERNAME=homestead/DB_USERNAME=root/g' environment > .env
  - sed 's/DB_PASSWORD=secret/DB_PASSWORD=/g' .env > environment
  - rm .env
  - mv environment .env

  # Add the service providers
  - sed 's/App\\Providers\\RouteServiceProvider\:\:class,/App\\Providers\\RouteServiceProvider\:\:class, Anla\\Skipper\\SkipperServiceProvider\:\:class, Intervention\\Image\\ImageServiceProvider\:\:class,/g' config/app.php > config/app-temp.php
  - rm config/app.php
  - mv config/app-temp.php config/app.php

  # Install skipper
  - php artisan skipper:install

  # Remove the default phpunit.xml and replace it with skipper phpunit.xml
  - rm phpunit.xml
  - cp vendor/anla/skipper/phpunit.xml phpunit.xml

script:
  # - vendor/bin/phpunit
